'use client'

import { useState } from 'react'
import Link from 'next/link'
import dynamic from 'next/dynamic'
import { useQuery } from '@tanstack/react-query'
import { CircularProgress } from '@/components/ui/CircularProgress'
import { StreakBadge } from '@/components/ui/StreakBadge'
import { computeRecovery } from '@/lib/recovery'
import { MODULES } from '@/components/os/Sidebar'
import { WeatherWidget, type WeatherData } from '@/components/dashboard/widgets/WeatherWidget'
import { HeatmapWidget } from '@/components/dashboard/widgets/HeatmapWidget'
import { ModulePageClient } from '@/components/os/ModulePageClient'
import { TappableWidget } from '@/components/os/TappableWidget'
import { OnboardingTour } from '@/components/OnboardingTour'
import { DoseDueBanner } from '@/components/os/DoseDueBanner'
import { GlobeSection } from '@/components/os/GlobeSection'
import { WorldClocksSection } from '@/components/os/WorldClocksSection'
import type { MainPageData } from '@/lib/pageData/main'

interface MainClientProps {
  initialData: MainPageData
  briefing: string | null
}

function MacroBar({ label, value, target }: { label: string; value: number; target: number }) {
  const pct = Math.min(100, target > 0 ? (value / target) * 100 : 0)
  return (
    <div className="flex flex-col gap-1">
      <div className="flex justify-between text-xs text-text-muted">
        <span>{label}</span>
        <span>{Math.round(value)}g / {Math.round(target)}g</span>
      </div>
      <div className="h-2 rounded-full bg-surface-elevated overflow-hidden">
        <div className="h-full rounded-full" style={{ width: `${pct}%`, background: 'var(--accent)' }} />
      </div>
    </div>
  )
}

function daysSince(dateStr: string | undefined): number | null {
  if (!dateStr) return null
  const then = new Date(dateStr + 'T12:00:00')
  const now = new Date()
  return Math.floor((now.getTime() - then.getTime()) / (1000 * 60 * 60 * 24))
}

const MainTrends = dynamic(() => import('./MainTrends'), {
  ssr: false,
  loading: () => (
    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
      {Array.from({ length: 4 }).map((_, i) => (
        <div key={i} className="rounded-2xl bg-surface border border-border p-4 h-[152px] animate-pulse">
          <div className="h-3 w-24 rounded bg-surface-elevated mb-3" />
          <div className="h-24 rounded bg-surface-elevated" />
        </div>
      ))}
    </div>
  ),
})

export function MainClient({ initialData, briefing }: MainClientProps) {
  // initialData (server-rendered, instant first paint) doubles as the
  // TanStack `initialData` — RealtimeSync invalidates ['main-summary'] on
  // any relevant DB change, which triggers a background refetch of this
  // exact query; the old data stays on screen until the new data resolves,
  // so numbers update in place with no remount/spinner/flash.
  const { data } = useQuery({
    queryKey: ['main-summary'],
    queryFn: async () => {
      const res = await fetch('/api/main-summary')
      if (!res.ok) throw new Error('Failed to load Main summary')
      return res.json() as Promise<MainPageData>
    },
    initialData,
  })
  const {
    stats, health, whoop, recentWorkouts, activeInjuries, trainToday, history, loggingStreak,
    weightTrend, sleepTrend, caloriesTrend, stepsTrend, recoveryStrainTrend, hrvTrend,
    hiddenWidgets, mounjaroEnabled, targets,
  } = data
  const hidden = new Set(hiddenWidgets)
  const [weather, setWeather] = useState<WeatherData | null>(null)
  const recovery = computeRecovery(stats, health, whoop)
  const recoveryColor = {
    poor: 'var(--negative)', fair: 'var(--warning)', good: 'var(--positive)', great: 'var(--accent)',
  }[recovery.level]

  const calories = stats?.calories ?? 0
  const sorted = [...recentWorkouts].sort((a, b) => b.date.localeCompare(a.date))
  const lastWorkout = sorted[0]
  const since = daysSince(lastWorkout?.date)
  const last7Load = sorted.filter((w) => (daysSince(w.date) ?? 99) < 7).length

  return (
    <div className="flex flex-col gap-6">
      <OnboardingTour />
      <h1 className="text-2xl font-bold text-text">How am I doing today</h1>

      {mounjaroEnabled && <DoseDueBanner mounjaroEnabled={mounjaroEnabled} />}

      {/* 1. AI daily briefing (the Coach) — one cached call/day, generated by cron */}
      <div className="rounded-2xl border p-5 flex gap-3" style={{ background: 'var(--accent-dim)', borderColor: 'var(--accent)' }}>
        <span className="text-xl shrink-0" aria-hidden>🧭</span>
        <div>
          <p className="text-xs font-semibold uppercase tracking-widest mb-1" style={{ color: 'var(--accent)' }}>Today's briefing</p>
          <p className="text-sm text-text leading-relaxed">
            {briefing ?? "No briefing yet — it generates automatically each morning once there's a day of data to work from."}
          </p>
        </div>
      </div>

      {/* 2. What should I train today — pure computation, no AI */}
      <div className="rounded-2xl bg-surface border border-border p-4 flex items-center gap-3">
        <span className="text-lg shrink-0" aria-hidden>🏋️</span>
        <p className="text-sm text-text-muted flex-1">{trainToday}</p>
        {activeInjuries.length > 0 && (
          <span className="text-[10px] px-2 py-1 rounded-full bg-negative/15 text-negative font-semibold shrink-0">
            {activeInjuries.length} active injur{activeInjuries.length === 1 ? 'y' : 'ies'}
          </span>
        )}
      </div>

      {!hidden.has('weather') && (
        <TappableWidget widgetId="weather" weather={weather}>
          <ModulePageClient w={8} h={5}>
            <WeatherWidget onData={setWeather} />
          </ModulePageClient>
        </TappableWidget>
      )}

      {/* 3. Today's rings — tappable into their modules */}
      <div data-tour="dashboard-grid" className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <Link href="/health" className="rounded-2xl bg-surface border border-border p-6 flex flex-col items-center gap-3 hover:border-border-strong transition-colors">
          <p className="text-xs font-semibold text-text-muted uppercase tracking-widest self-start">Recovery</p>
          <CircularProgress value={recovery.score} max={100} size={160} strokeWidth={10} color={recoveryColor} unit="recovery" countUp />
          <p className="text-sm text-text-muted text-center">{recovery.explanation}</p>
        </Link>

        <Link href="/food" className="rounded-2xl bg-surface border border-border p-6 flex flex-col items-center gap-4 hover:border-border-strong transition-colors">
          <p className="text-xs font-semibold text-text-muted uppercase tracking-widest self-start">Nutrition today</p>
          <CircularProgress value={calories} max={targets.calorie_target} size={140} strokeWidth={9} unit="kcal" countUp showTargetGlow />
          <div className="w-full flex flex-col gap-2">
            <MacroBar label="Protein" value={Number(stats?.protein_g ?? 0)} target={targets.protein_target_g} />
            <MacroBar label="Carbs" value={Number(stats?.carbs_g ?? 0)} target={targets.carbs_target_g} />
            <MacroBar label="Fat" value={Number(stats?.fat_g ?? 0)} target={targets.fat_target_g} />
          </div>
        </Link>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <Link href="/gym" className="rounded-2xl bg-surface border border-border p-5 flex flex-col gap-2 hover:border-border-strong transition-colors">
          <p className="text-xs font-semibold text-text-muted uppercase tracking-widest">Training status</p>
          {lastWorkout ? (
            <>
              <p className="text-lg font-bold text-text">{lastWorkout.description}</p>
              <p className="text-sm text-text-muted">
                {since === 0 ? 'Today' : since === 1 ? '1 day ago' : `${since} days ago`}
              </p>
            </>
          ) : (
            <p className="text-sm text-text-subtle">No recent workouts logged</p>
          )}
          <p className="text-xs text-text-faint mt-1">{last7Load} session{last7Load === 1 ? '' : 's'} in the last 7 days</p>
        </Link>

        <Link href="/health" className="rounded-2xl bg-surface border border-border p-5 flex flex-col gap-3 hover:border-border-strong transition-colors">
          <p className="text-xs font-semibold text-text-muted uppercase tracking-widest">Key vitals</p>
          <div className="grid grid-cols-3 gap-3">
            <div>
              <p className="text-xl font-bold text-text tabular-nums">{whoop?.hrv_rmssd_milli != null ? Math.round(whoop.hrv_rmssd_milli) : '—'}</p>
              <p className="text-[11px] text-text-subtle">HRV ms</p>
            </div>
            <div>
              <p className="text-xl font-bold text-text tabular-nums">{whoop?.resting_hr ?? '—'}</p>
              <p className="text-[11px] text-text-subtle">RHR bpm</p>
            </div>
            <div>
              <p className="text-xl font-bold text-text tabular-nums">{stats?.sleep_hours ?? '—'}</p>
              <p className="text-[11px] text-text-subtle">Sleep hrs</p>
            </div>
          </div>
        </Link>
      </div>

      {/* 4. Trend graphs — dynamically imported, recharts shouldn't block the initial paint above */}
      <MainTrends
        weightTrend={weightTrend}
        sleepTrend={sleepTrend}
        caloriesTrend={caloriesTrend}
        stepsTrend={stepsTrend}
        recoveryStrainTrend={recoveryStrainTrend}
        hrvTrend={hrvTrend}
        calorieTarget={targets.calorie_target}
      />

      {/* 5. Year heatmap strip — reused, not forked */}
      {!hidden.has('heatmap') && (
        <div>
          <p className="text-xs font-semibold text-text-muted uppercase tracking-widest mb-2">Activity</p>
          <TappableWidget widgetId="heatmap" history={history}>
            <ModulePageClient w={12} h={5}>
              <HeatmapWidget history={history} workouts={recentWorkouts} calorieTarget={targets.calorie_target} />
            </ModulePageClient>
          </TappableWidget>
        </div>
      )}

      {/* World: visited-countries globe + world clocks */}
      <div>
        <p className="text-xs font-semibold text-text-muted uppercase tracking-widest mb-2">World</p>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <GlobeSection />
          <WorldClocksSection />
        </div>
      </div>

      {/* 6. Streak / consistency counter */}
      {loggingStreak >= 2 && (
        <div className="flex items-center gap-2">
          <StreakBadge count={loggingStreak} label="days logged in a row" />
        </div>
      )}

      {/* 7. Quick-nav tiles */}
      <div>
        <p className="text-xs font-semibold text-text-muted uppercase tracking-widest mb-2">Modules</p>
        <div className="grid grid-cols-3 sm:grid-cols-4 md:grid-cols-5 gap-3">
          {MODULES.filter((m) => m.href !== '/main').map((m) => (
            <Link
              key={m.href}
              href={m.href}
              className="rounded-xl bg-surface border border-border p-4 flex flex-col items-center gap-1.5 hover:border-border-strong transition-colors"
            >
              <span className="text-2xl" aria-hidden>{m.icon}</span>
              <span className="text-xs font-medium text-text-muted">{m.label}</span>
            </Link>
          ))}
        </div>
      </div>
    </div>
  )
}
