'use client'

import { useState } from 'react'
import Link from 'next/link'
import {
  LineChart, Line, BarChart, Bar, Cell, ComposedChart, XAxis, YAxis, Tooltip, ResponsiveContainer, ReferenceLine,
} from 'recharts'
import { CircularProgress } from '@/components/ui/CircularProgress'
import { StreakBadge } from '@/components/ui/StreakBadge'
import { computeRecovery } from '@/lib/recovery'
import { MODULES } from '@/components/os/Sidebar'
import { WeatherWidget, type WeatherData } from '@/components/dashboard/widgets/WeatherWidget'
import { HeatmapWidget } from '@/components/dashboard/widgets/HeatmapWidget'
import { ModulePageClient } from '@/components/os/ModulePageClient'
import { TappableWidget } from '@/components/os/TappableWidget'
import type { DailyStats, HealthStatus, WorkoutSession, Injury } from '@/lib/db/queries'
import type { WhoopMetrics } from '@/lib/db/whoop'

interface MainClientProps {
  stats: DailyStats | null
  health: HealthStatus | null
  whoop: WhoopMetrics | null
  recentWorkouts: WorkoutSession[]
  briefing: string | null
  activeInjuries: Injury[]
  trainToday: string
  history: DailyStats[]
  loggingStreak: number
  weightTrend: { date: string; value: number }[]
  sleepTrend: { date: string; hours: number }[]
  caloriesTrend: { date: string; calories: number }[]
  stepsTrend: { date: string; steps: number }[]
  recoveryStrainTrend: { date: string; recovery: number; strain: number }[]
  hrvTrend: { date: string; hrv: number }[]
  targets: {
    calorie_target: number
    protein_target_g: number
    carbs_target_g: number
    fat_target_g: number
  }
}

function MacroBar({ label, value, target }: { label: string; value: number; target: number }) {
  const pct = Math.min(100, target > 0 ? (value / target) * 100 : 0)
  return (
    <div className="flex flex-col gap-1">
      <div className="flex justify-between text-xs text-text-muted">
        <span>{label}</span>
        <span>{Math.round(value)}g / {Math.round(target)}g</span>
      </div>
      <div className="h-2 rounded-full bg-surface-elevated overflow-hidden">
        <div className="h-full rounded-full" style={{ width: `${pct}%`, background: 'var(--accent)' }} />
      </div>
    </div>
  )
}

function daysSince(dateStr: string | undefined): number | null {
  if (!dateStr) return null
  const then = new Date(dateStr + 'T12:00:00')
  const now = new Date()
  return Math.floor((now.getTime() - then.getTime()) / (1000 * 60 * 60 * 24))
}

function fmtDate(d: string) {
  return new Date(d + 'T12:00:00').toLocaleDateString('en-GB', { day: 'numeric', month: 'short' })
}

function TrendCard({ title, href, children }: { title: string; href: string; children: React.ReactNode }) {
  return (
    <Link href={href} className="rounded-2xl bg-surface border border-border p-4 flex flex-col gap-2 hover:border-border-strong transition-colors block">
      <p className="text-xs font-semibold text-text-muted uppercase tracking-widest">{title}</p>
      {children}
    </Link>
  )
}

const tooltipStyle = { background: 'var(--surface-elevated)', border: '1px solid var(--border-strong)', borderRadius: 8, fontSize: 12 }
const axisTick = { fontSize: 10, fill: 'var(--text-faint)' }

export function MainClient({
  stats, health, whoop, recentWorkouts, briefing, activeInjuries, trainToday, history, loggingStreak,
  weightTrend, sleepTrend, caloriesTrend, stepsTrend, recoveryStrainTrend, hrvTrend, targets,
}: MainClientProps) {
  const [weather, setWeather] = useState<WeatherData | null>(null)
  const recovery = computeRecovery(stats, health, whoop)
  const recoveryColor = {
    poor: 'var(--negative)', fair: 'var(--warning)', good: 'var(--positive)', great: 'var(--accent)',
  }[recovery.level]

  const calories = stats?.calories ?? 0
  const sorted = [...recentWorkouts].sort((a, b) => b.date.localeCompare(a.date))
  const lastWorkout = sorted[0]
  const since = daysSince(lastWorkout?.date)
  const last7Load = sorted.filter((w) => (daysSince(w.date) ?? 99) < 7).length

  return (
    <div className="flex flex-col gap-6">
      <h1 className="text-2xl font-bold text-text">How am I doing today</h1>

      {/* 1. AI daily briefing (the Coach) — one cached call/day, generated by cron */}
      <div className="rounded-2xl border p-5 flex gap-3" style={{ background: 'var(--accent-dim)', borderColor: 'var(--accent)' }}>
        <span className="text-xl shrink-0" aria-hidden>🧭</span>
        <div>
          <p className="text-xs font-semibold uppercase tracking-widest mb-1" style={{ color: 'var(--accent)' }}>Today's briefing</p>
          <p className="text-sm text-text leading-relaxed">
            {briefing ?? "No briefing yet — it generates automatically each morning once there's a day of data to work from."}
          </p>
        </div>
      </div>

      {/* 2. What should I train today — pure computation, no AI */}
      <div className="rounded-2xl bg-surface border border-border p-4 flex items-center gap-3">
        <span className="text-lg shrink-0" aria-hidden>🏋️</span>
        <p className="text-sm text-text-muted flex-1">{trainToday}</p>
        {activeInjuries.length > 0 && (
          <span className="text-[10px] px-2 py-1 rounded-full bg-red-500/15 text-red-400 font-semibold shrink-0">
            {activeInjuries.length} active injur{activeInjuries.length === 1 ? 'y' : 'ies'}
          </span>
        )}
      </div>

      <TappableWidget widgetId="weather" weather={weather}>
        <ModulePageClient w={8} h={5}>
          <WeatherWidget onData={setWeather} />
        </ModulePageClient>
      </TappableWidget>

      {/* 3. Today's rings — tappable into their modules */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <Link href="/health" className="rounded-2xl bg-surface border border-border p-6 flex flex-col items-center gap-3 hover:border-border-strong transition-colors">
          <p className="text-xs font-semibold text-text-muted uppercase tracking-widest self-start">Recovery</p>
          <CircularProgress value={recovery.score} max={100} size={160} strokeWidth={10} color={recoveryColor} unit="recovery" countUp />
          <p className="text-sm text-text-muted text-center">{recovery.explanation}</p>
        </Link>

        <Link href="/food" className="rounded-2xl bg-surface border border-border p-6 flex flex-col items-center gap-4 hover:border-border-strong transition-colors">
          <p className="text-xs font-semibold text-text-muted uppercase tracking-widest self-start">Nutrition today</p>
          <CircularProgress value={calories} max={targets.calorie_target} size={140} strokeWidth={9} unit="kcal" countUp showTargetGlow />
          <div className="w-full flex flex-col gap-2">
            <MacroBar label="Protein" value={Number(stats?.protein_g ?? 0)} target={targets.protein_target_g} />
            <MacroBar label="Carbs" value={Number(stats?.carbs_g ?? 0)} target={targets.carbs_target_g} />
            <MacroBar label="Fat" value={Number(stats?.fat_g ?? 0)} target={targets.fat_target_g} />
          </div>
        </Link>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <Link href="/gym" className="rounded-2xl bg-surface border border-border p-5 flex flex-col gap-2 hover:border-border-strong transition-colors">
          <p className="text-xs font-semibold text-text-muted uppercase tracking-widest">Training status</p>
          {lastWorkout ? (
            <>
              <p className="text-lg font-bold text-text">{lastWorkout.description}</p>
              <p className="text-sm text-text-muted">
                {since === 0 ? 'Today' : since === 1 ? '1 day ago' : `${since} days ago`}
              </p>
            </>
          ) : (
            <p className="text-sm text-text-subtle">No recent workouts logged</p>
          )}
          <p className="text-xs text-text-faint mt-1">{last7Load} session{last7Load === 1 ? '' : 's'} in the last 7 days</p>
        </Link>

        <Link href="/health" className="rounded-2xl bg-surface border border-border p-5 flex flex-col gap-3 hover:border-border-strong transition-colors">
          <p className="text-xs font-semibold text-text-muted uppercase tracking-widest">Key vitals</p>
          <div className="grid grid-cols-3 gap-3">
            <div>
              <p className="text-xl font-bold text-text tabular-nums">{whoop?.hrv_rmssd_milli != null ? Math.round(whoop.hrv_rmssd_milli) : '—'}</p>
              <p className="text-[11px] text-text-subtle">HRV ms</p>
            </div>
            <div>
              <p className="text-xl font-bold text-text tabular-nums">{whoop?.resting_hr ?? '—'}</p>
              <p className="text-[11px] text-text-subtle">RHR bpm</p>
            </div>
            <div>
              <p className="text-xl font-bold text-text tabular-nums">{stats?.sleep_hours ?? '—'}</p>
              <p className="text-[11px] text-text-subtle">Sleep hrs</p>
            </div>
          </div>
        </Link>
      </div>

      {/* 4. Trend graphs — tappable into the relevant module */}
      <div>
        <p className="text-xs font-semibold text-text-muted uppercase tracking-widest mb-2">Trends</p>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {weightTrend.length > 1 && (
            <TrendCard title="Weight (90d)" href="/health">
              <div style={{ width: '100%', height: 120 }}>
                <ResponsiveContainer>
                  <LineChart data={weightTrend}>
                    <XAxis dataKey="date" tickFormatter={fmtDate} tick={axisTick} minTickGap={30} />
                    <YAxis tick={axisTick} width={32} domain={['dataMin - 1', 'dataMax + 1']} />
                    <Tooltip labelFormatter={(l) => fmtDate(String(l))} contentStyle={tooltipStyle} />
                    <Line type="monotone" dataKey="value" stroke="var(--accent)" strokeWidth={2} dot={false} />
                  </LineChart>
                </ResponsiveContainer>
              </div>
            </TrendCard>
          )}

          {recoveryStrainTrend.length > 1 && (
            <TrendCard title="Recovery & strain (14d)" href="/health">
              <div style={{ width: '100%', height: 120 }}>
                <ResponsiveContainer>
                  <ComposedChart data={recoveryStrainTrend}>
                    <XAxis dataKey="date" tickFormatter={fmtDate} tick={axisTick} minTickGap={30} />
                    <YAxis tick={axisTick} width={28} />
                    <Tooltip labelFormatter={(l) => fmtDate(String(l))} contentStyle={tooltipStyle} />
                    <Bar dataKey="strain" fill="var(--warning)" opacity={0.5} barSize={6} />
                    <Line type="monotone" dataKey="recovery" stroke="var(--positive)" strokeWidth={2} dot={false} />
                  </ComposedChart>
                </ResponsiveContainer>
              </div>
            </TrendCard>
          )}

          {sleepTrend.length > 1 && (
            <TrendCard title="Sleep vs 8h target (7d)" href="/health">
              <div style={{ width: '100%', height: 120 }}>
                <ResponsiveContainer>
                  <BarChart data={sleepTrend}>
                    <XAxis dataKey="date" tickFormatter={fmtDate} tick={axisTick} />
                    <YAxis tick={axisTick} width={24} />
                    <Tooltip labelFormatter={(l) => fmtDate(String(l))} contentStyle={tooltipStyle} />
                    <ReferenceLine y={8} stroke="var(--text-faint)" strokeDasharray="3 3" />
                    <Bar dataKey="hours" radius={[4, 4, 0, 0]}>
                      {sleepTrend.map((d, i) => (
                        <Cell key={i} fill={d.hours >= 8 ? 'var(--positive)' : 'var(--warning)'} />
                      ))}
                    </Bar>
                  </BarChart>
                </ResponsiveContainer>
              </div>
            </TrendCard>
          )}

          {caloriesTrend.length > 1 && (
            <TrendCard title="Calories vs target (7d)" href="/food">
              <div style={{ width: '100%', height: 120 }}>
                <ResponsiveContainer>
                  <BarChart data={caloriesTrend}>
                    <XAxis dataKey="date" tickFormatter={fmtDate} tick={axisTick} />
                    <YAxis tick={axisTick} width={36} />
                    <Tooltip labelFormatter={(l) => fmtDate(String(l))} contentStyle={tooltipStyle} />
                    <ReferenceLine y={targets.calorie_target} stroke="var(--text-faint)" strokeDasharray="3 3" />
                    <Bar dataKey="calories" radius={[4, 4, 0, 0]}>
                      {caloriesTrend.map((d, i) => (
                        <Cell key={i} fill={d.calories <= targets.calorie_target ? 'var(--positive)' : 'var(--negative)'} />
                      ))}
                    </Bar>
                  </BarChart>
                </ResponsiveContainer>
              </div>
            </TrendCard>
          )}

          {hrvTrend.length > 1 && (
            <TrendCard title="HRV (14d)" href="/health">
              <div style={{ width: '100%', height: 100 }}>
                <ResponsiveContainer>
                  <LineChart data={hrvTrend}>
                    <XAxis dataKey="date" tickFormatter={fmtDate} tick={axisTick} minTickGap={30} />
                    <YAxis tick={axisTick} width={28} />
                    <Tooltip labelFormatter={(l) => fmtDate(String(l))} contentStyle={tooltipStyle} />
                    <Line type="monotone" dataKey="hrv" stroke="var(--accent)" strokeWidth={2} dot={false} />
                  </LineChart>
                </ResponsiveContainer>
              </div>
            </TrendCard>
          )}

          {stepsTrend.length > 1 && (
            <TrendCard title="Steps (7d)" href="/health">
              <div style={{ width: '100%', height: 100 }}>
                <ResponsiveContainer>
                  <BarChart data={stepsTrend}>
                    <XAxis dataKey="date" tickFormatter={fmtDate} tick={axisTick} />
                    <YAxis tick={axisTick} width={36} />
                    <Tooltip labelFormatter={(l) => fmtDate(String(l))} contentStyle={tooltipStyle} />
                    <Bar dataKey="steps" fill="var(--accent)" radius={[4, 4, 0, 0]} />
                  </BarChart>
                </ResponsiveContainer>
              </div>
            </TrendCard>
          )}
        </div>
      </div>

      {/* 5. Year heatmap strip — reused, not forked */}
      <div>
        <p className="text-xs font-semibold text-text-muted uppercase tracking-widest mb-2">Activity</p>
        <TappableWidget widgetId="heatmap" history={history}>
          <ModulePageClient w={12} h={5}>
            <HeatmapWidget history={history} workouts={recentWorkouts} calorieTarget={targets.calorie_target} />
          </ModulePageClient>
        </TappableWidget>
      </div>

      {/* 6. Streak / consistency counter */}
      {loggingStreak >= 2 && (
        <div className="flex items-center gap-2">
          <StreakBadge count={loggingStreak} label="days logged in a row" />
        </div>
      )}

      {/* 7. Quick-nav tiles */}
      <div>
        <p className="text-xs font-semibold text-text-muted uppercase tracking-widest mb-2">Modules</p>
        <div className="grid grid-cols-3 sm:grid-cols-4 md:grid-cols-5 gap-3">
          {MODULES.filter((m) => m.href !== '/main').map((m) => (
            <Link
              key={m.href}
              href={m.href}
              className="rounded-xl bg-surface border border-border p-4 flex flex-col items-center gap-1.5 hover:border-border-strong transition-colors"
            >
              <span className="text-2xl" aria-hidden>{m.icon}</span>
              <span className="text-xs font-medium text-text-muted">{m.label}</span>
            </Link>
          ))}
        </div>
      </div>
    </div>
  )
}
